// DeferredLighting shader parameters. Field order defines the GPU layout.
HYP_SHADER_CONTRACT(DeferredLighting, 1)

HYP_UNIFORM_BEGIN(DeferredLightV1, DeferredLighting)
	HYP_UNIFORM_FIELD(float4x4, InverseViewProjection, View)
	HYP_UNIFORM_FIELD(float4, Viewport, View)
	HYP_UNIFORM_FIELD(float2, DepthRange, View)
	HYP_UNIFORM_FIELD(float3, Eye, View)
	HYP_SEMANTIC_CONVENTION("World-space eye position")
	HYP_UNIFORM_FIELD(float3, LightDirection, Scene)
	HYP_SEMANTIC_CONVENTION("Unit world-space surface-to-light vector")
	HYP_UNIFORM_FIELD(float3, LightColor, Scene)
	HYP_SEMANTIC_CONVENTION("Linear RGB radiance")
	HYP_UNIFORM_FIELD(float3, Ambient, Scene)
	HYP_SEMANTIC_CONVENTION("Linear ambient RGB radiance")
HYP_UNIFORM_END()

HYP_UNIFORM_BEGIN(LocalVolumeV1, LocalVolume)
	HYP_UNIFORM_FIELD(float4x4, ViewProjection, View)
	HYP_SEMANTIC_CONVENTION("Column-vector world to clip")
	HYP_UNIFORM_FIELD(float4x4, World, Object)
	HYP_SEMANTIC_CONVENTION("Column-vector local to world")
HYP_UNIFORM_END()

HYP_UNIFORM_BEGIN(LocalLightV1, LocalLighting)
	HYP_UNIFORM_FIELD(float4x4, InverseViewProjection, View)
	HYP_UNIFORM_FIELD(float4, Viewport, View)
	HYP_UNIFORM_FIELD(float2, DepthRange, View)
	HYP_UNIFORM_FIELD(float3, Eye, View)
	HYP_SEMANTIC_CONVENTION("World-space eye position")
	HYP_UNIFORM_FIELD(float3, Position, Draw)
	HYP_UNIFORM_FIELD(float3, Radiance, Draw)
	HYP_UNIFORM_FIELD(float3, Direction, Draw)
	HYP_UNIFORM_FIELD(float4, ConeRange, Draw)
HYP_UNIFORM_END()

HYP_UNIFORM_BEGIN(GBufferDebugV1, GBufferDebug)
	HYP_UNIFORM_FIELD(uint, Mode, Pass)
HYP_UNIFORM_END()

HYP_RESOURCE_NAMESPACE("Engine.Pass")
HYP_TEXTURE_2D(float4, GBuffer0, Pass)
HYP_TEXTURE_2D(float4, GBuffer1, Pass)
HYP_TEXTURE_2D(float4, GBuffer2, Pass)
HYP_TEXTURE_2D(float4, GBuffer3, Pass)
HYP_TEXTURE_2D(float, SceneDepth, Pass)
HYP_TEXTURE_2D(float, ContactVisibility, Pass)
HYP_SAMPLER(ContactSampler, Pass)
