add_executable(hyperion_editor Private/Main.cpp Private/Editor.manifest)
hyp_executable(hyperion_editor)
target_sources(hyperion_editor PRIVATE "${PROJECT_SOURCE_DIR}/Source/Applications/Resources/Hyperion.rc")
target_include_directories(hyperion_editor PRIVATE "${PROJECT_SOURCE_DIR}/Source/Applications/Resources")
target_link_libraries(hyperion_editor PRIVATE hyperion_editor_plugin hyperion_rhi_d3d12 hyperion_core)
target_compile_definitions(hyperion_editor PRIVATE HYP_SOURCE_DIR="${PROJECT_SOURCE_DIR}")
set_target_properties(hyperion_editor PROPERTIES VS_DEBUGGER_WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}")
