// Pbr shader parameters. Field order defines the GPU layout.
HYP_SHADER_CONTRACT(Pbr, 1)

HYP_CONTRACT_POLICY(Pbr, false, false)

HYP_UNIFORM_FLAT_BEGIN(HyperionMaterialV1)
	HYP_UNIFORM_WIRE_NAMESPACE("Pbr")
	HYP_UNIFORM_FIELD(float4, BaseColor, Material)
	HYP_SEMANTIC_WIRE("Pbr.BaseColorFactor")
	HYP_SEMANTIC_CONVENTION("Linear RGBA multiplier")
	HYP_SEMANTIC_POLICY(Pbr, false, false, Color)
	HYP_UNIFORM_FIELD(float3, Emissive, Material)
	HYP_SEMANTIC_WIRE("Pbr.EmissiveFactor")
	HYP_SEMANTIC_CONVENTION("Linear RGB multiplier")
	HYP_SEMANTIC_POLICY(Pbr, false, false, HdrColor)
	HYP_UNIFORM_FIELD(float, NormalScale, Material)
	HYP_SEMANTIC_CONVENTION("Tangent-space normal XY multiplier")
	HYP_UNIFORM_FIELD(float, Metallic, Material)
	HYP_SEMANTIC_WIRE("Pbr.MetallicFactor")
	HYP_SEMANTIC_CONVENTION("Metallic scalar")
	HYP_UNIFORM_FIELD(float, Roughness, Material)
	HYP_SEMANTIC_WIRE("Pbr.RoughnessFactor")
	HYP_SEMANTIC_CONVENTION("Perceptual roughness")
	HYP_UNIFORM_FIELD(float, OcclusionStrength, Material)
	HYP_SEMANTIC_CONVENTION("Occlusion blend strength")
	HYP_UNIFORM_FIELD(float, AlphaCutoff, Material)
	HYP_SEMANTIC_CONVENTION("Masked alpha threshold")
	HYP_UNIFORM_FIELD(uint, BaseColorUv, Material)
	HYP_SEMANTIC_WIRE("Pbr.BaseColorUvSet")
	HYP_SEMANTIC_CONVENTION("Vertex texture coordinate set 0 or 1")
	HYP_SEMANTIC_POLICY(Pbr, false, false, UvSet)
	HYP_UNIFORM_FIELD(uint, MetallicRoughnessUv, Material)
	HYP_SEMANTIC_WIRE("Pbr.MetallicRoughnessUvSet")
	HYP_SEMANTIC_CONVENTION("Vertex texture coordinate set 0 or 1")
	HYP_SEMANTIC_POLICY(Pbr, false, false, UvSet)
	HYP_UNIFORM_FIELD(uint, NormalUv, Material)
	HYP_SEMANTIC_WIRE("Pbr.NormalUvSet")
	HYP_SEMANTIC_CONVENTION("Vertex texture coordinate set 0 or 1")
	HYP_SEMANTIC_POLICY(Pbr, false, false, UvSet)
	HYP_UNIFORM_FIELD(uint, OcclusionUv, Material)
	HYP_SEMANTIC_WIRE("Pbr.OcclusionUvSet")
	HYP_SEMANTIC_CONVENTION("Vertex texture coordinate set 0 or 1")
	HYP_SEMANTIC_POLICY(Pbr, false, false, UvSet)
	HYP_UNIFORM_FIELD(uint, EmissiveUv, Material)
	HYP_SEMANTIC_WIRE("Pbr.EmissiveUvSet")
	HYP_SEMANTIC_CONVENTION("Vertex texture coordinate set 0 or 1")
	HYP_SEMANTIC_POLICY(Pbr, false, false, UvSet)
	HYP_UNIFORM_FIELD(uint, AlphaMode, Material)
	HYP_SEMANTIC_CONVENTION("0 opaque, 1 masked, 2 blended")
	HYP_UNIFORM_FIELD(bool, bDoubleSided, Material)
	HYP_SEMANTIC_WIRE("Pbr.DoubleSided")
	HYP_SEMANTIC_CONVENTION("Flip the back-face shading normal")
	HYP_UNIFORM_FIELD(bool, bUnlit, Material)
	HYP_SEMANTIC_WIRE("Pbr.Unlit")
	HYP_SEMANTIC_CONVENTION("Use unlit base color and emissive")
	HYP_UNIFORM_FIELD(bool, bHasNormal, Material)
	HYP_SEMANTIC_WIRE("Pbr.HasNormal")
	HYP_SEMANTIC_CONVENTION("Enable tangent-space normal sampling")
HYP_UNIFORM_END()

HYP_TEXTURE_2D(float4, BaseColorTexture, Material)
HYP_SEMANTIC_CONVENTION("sRGB source decoded to linear")
HYP_SEMANTIC_ALIAS("ALBEDO_TEXTURE")
HYP_SAMPLER(BaseColorSampler, Material)
HYP_SEMANTIC_CONVENTION("glTF texture sampler")
HYP_TEXTURE_2D(float4, MetallicRoughnessTexture, Material)
HYP_SEMANTIC_CONVENTION("Linear data channels")
HYP_SEMANTIC_ALIAS("METALLIC_ROUGHNESS_TEXTURE")
HYP_SAMPLER(MetallicRoughnessSampler, Material)
HYP_SEMANTIC_CONVENTION("glTF texture sampler")
HYP_TEXTURE_2D(float4, NormalTexture, Material)
HYP_SEMANTIC_CONVENTION("Linear tangent-space XYZ normal")
HYP_SEMANTIC_ALIAS("NORMAL_TEXTURE")
HYP_SAMPLER(NormalSampler, Material)
HYP_SEMANTIC_CONVENTION("glTF texture sampler")
HYP_TEXTURE_2D(float4, OcclusionTexture, Material)
HYP_SEMANTIC_CONVENTION("Linear data channels")
HYP_SEMANTIC_ALIAS("OCCLUSION_TEXTURE")
HYP_SAMPLER(OcclusionSampler, Material)
HYP_SEMANTIC_CONVENTION("glTF texture sampler")
HYP_TEXTURE_2D(float4, EmissiveTexture, Material)
HYP_SEMANTIC_CONVENTION("sRGB source decoded to linear")
HYP_SEMANTIC_ALIAS("EMISSIVE_TEXTURE")
HYP_SAMPLER(EmissiveSampler, Material)
HYP_SEMANTIC_CONVENTION("glTF texture sampler")

HYP_UNIFORM_ALIAS(MaterialInfo, HyperionMaterialV1)
HYP_INSTANCE_ARRAY(HyperionMaterialV1, SurfaceInstances)
