add_library(hyperion_reflection STATIC Private/Adapters/JsonSerialization.cpp Private/Record.cpp Private/Inspection.cpp)
hyp_module(hyperion_reflection)
target_sources(hyperion_reflection PRIVATE Private/SelectionInspection.cpp)
target_link_libraries(hyperion_reflection PRIVATE nlohmann_json::nlohmann_json)
