// Environment shader parameters. Field order defines the GPU layout.
HYP_SHADER_CONTRACT(Environment, 1)

HYP_CONTRACT_POLICY(Environment, true, true)

HYP_UNIFORM_FLAT_BEGIN(EnvironmentV1)
	HYP_UNIFORM_WIRE_NAMESPACE("Engine.Scene")
	HYP_UNIFORM_FIELD(float4, EnvironmentControl, Scene)
	HYP_SEMANTIC_CONVENTION("Environment V1: ready/intensity/max mip, inverse Y rotation, cosine-convolved SH9 RGB")
	HYP_UNIFORM_FIELD(float4, EnvironmentRotation, Scene)
	HYP_SEMANTIC_CONVENTION("Environment V1: ready/intensity/max mip, inverse Y rotation, cosine-convolved SH9 RGB")
	HYP_UNIFORM_FIELD(float4, EnvironmentSh0, Scene)
	HYP_SEMANTIC_CONVENTION("Environment V1: ready/intensity/max mip, inverse Y rotation, cosine-convolved SH9 RGB")
	HYP_UNIFORM_FIELD(float4, EnvironmentSh1, Scene)
	HYP_SEMANTIC_CONVENTION("Environment V1: ready/intensity/max mip, inverse Y rotation, cosine-convolved SH9 RGB")
	HYP_UNIFORM_FIELD(float4, EnvironmentSh2, Scene)
	HYP_SEMANTIC_CONVENTION("Environment V1: ready/intensity/max mip, inverse Y rotation, cosine-convolved SH9 RGB")
	HYP_UNIFORM_FIELD(float4, EnvironmentSh3, Scene)
	HYP_SEMANTIC_CONVENTION("Environment V1: ready/intensity/max mip, inverse Y rotation, cosine-convolved SH9 RGB")
	HYP_UNIFORM_FIELD(float4, EnvironmentSh4, Scene)
	HYP_SEMANTIC_CONVENTION("Environment V1: ready/intensity/max mip, inverse Y rotation, cosine-convolved SH9 RGB")
	HYP_UNIFORM_FIELD(float4, EnvironmentSh5, Scene)
	HYP_SEMANTIC_CONVENTION("Environment V1: ready/intensity/max mip, inverse Y rotation, cosine-convolved SH9 RGB")
	HYP_UNIFORM_FIELD(float4, EnvironmentSh6, Scene)
	HYP_SEMANTIC_CONVENTION("Environment V1: ready/intensity/max mip, inverse Y rotation, cosine-convolved SH9 RGB")
	HYP_UNIFORM_FIELD(float4, EnvironmentSh7, Scene)
	HYP_SEMANTIC_CONVENTION("Environment V1: ready/intensity/max mip, inverse Y rotation, cosine-convolved SH9 RGB")
	HYP_UNIFORM_FIELD(float4, EnvironmentSh8, Scene)
	HYP_SEMANTIC_CONVENTION("Environment V1: ready/intensity/max mip, inverse Y rotation, cosine-convolved SH9 RGB")
HYP_UNIFORM_END()

HYP_RESOURCE_NAMESPACE("Engine.Scene")
HYP_TEXTURE_CUBE(float4, EnvironmentSpecular, Scene)
HYP_SEMANTIC_CONVENTION("Linear GGX environment split-sum resources")
HYP_TEXTURE_2D(float4, EnvironmentBrdf, Scene)
HYP_SEMANTIC_CONVENTION("Linear GGX environment split-sum resources")
HYP_SAMPLER(EnvironmentSampler, Scene)
HYP_SEMANTIC_CONVENTION("Linear GGX environment split-sum resources")

HYP_UNIFORM_ALIAS(EnvironmentInfo, EnvironmentV1)
