// Shadow shader parameters. Field order defines the GPU layout.
HYP_SHADER_CONTRACT(Shadow, 1)

HYP_CONTRACT_POLICY(Shadow, false, false)

HYP_UNIFORM_FLAT_BEGIN(ShadowViewV1)
	HYP_UNIFORM_WIRE_NAMESPACE("Engine.View")
	HYP_UNIFORM_FIELD(float4x4, ShadowMatrix0, View)
	HYP_SEMANTIC_CONVENTION("Column-vector world to shadow clip, zero-to-one depth")
	HYP_UNIFORM_FIELD(float4x4, ShadowMatrix1, View)
	HYP_SEMANTIC_CONVENTION("Column-vector world to shadow clip, zero-to-one depth")
	HYP_UNIFORM_FIELD(float4x4, ShadowMatrix2, View)
	HYP_SEMANTIC_CONVENTION("Column-vector world to shadow clip, zero-to-one depth")
	HYP_UNIFORM_FIELD(float4x4, ShadowMatrix3, View)
	HYP_SEMANTIC_CONVENTION("Column-vector world to shadow clip, zero-to-one depth")
	HYP_UNIFORM_FIELD(float4, ShadowSplits, View)
	HYP_SEMANTIC_CONVENTION("Cascaded directional shadow contract V1")
	HYP_UNIFORM_FIELD(float4, ShadowTexels, View)
	HYP_SEMANTIC_CONVENTION("Cascaded directional shadow contract V1")
	HYP_UNIFORM_FIELD(float4, ShadowRanges, View)
	HYP_SEMANTIC_CONVENTION("Cascaded directional shadow contract V1")
	HYP_UNIFORM_FIELD(float4, ShadowCamera, View)
	HYP_SEMANTIC_CONVENTION("Cascaded directional shadow contract V1")
	HYP_UNIFORM_FIELD(float4, ShadowFilter, View)
	HYP_SEMANTIC_CONVENTION("Cascaded directional shadow contract V1")
	HYP_UNIFORM_FIELD(float4, ShadowControl, View)
	HYP_SEMANTIC_CONVENTION("Cascaded directional shadow contract V1")
HYP_UNIFORM_END()

HYP_RESOURCE_NAMESPACE("Engine.View")
HYP_TEXTURE_2D(float, ShadowDepth0, View)
HYP_SEMANTIC_CONVENTION("Directional cascade sampled D32 depth")
HYP_TEXTURE_2D(float, ShadowDepth1, View)
HYP_SEMANTIC_CONVENTION("Directional cascade sampled D32 depth")
HYP_TEXTURE_2D(float, ShadowDepth2, View)
HYP_SEMANTIC_CONVENTION("Directional cascade sampled D32 depth")
HYP_TEXTURE_2D(float, ShadowDepth3, View)
HYP_SEMANTIC_CONVENTION("Directional cascade sampled D32 depth")
HYP_COMPARISON_SAMPLER(ShadowSampler, View)
HYP_SEMANTIC_CONVENTION("Less-equal depth comparison sampler")

HYP_UNIFORM_ALIAS(ShadowViewInfo, ShadowViewV1)
