add_library(hyperion_shaders STATIC Private/Adapters/ShaderCompiler.cpp Private/Adapters/DxilReflection.cpp Private/Adapters/SpirvReflection.cpp)
hyp_module(hyperion_shaders)
target_link_libraries(hyperion_shaders PUBLIC hyperion_core PRIVATE spirv-cross-msl spirv-cross-core "${HYP_DEPS}/dxc/lib/x64/dxcompiler.lib" bcrypt)
target_include_directories(hyperion_shaders SYSTEM PRIVATE "${HYP_DEPS}/dxc/inc")
file(READ "${HYP_DEPS}/dxc/.hyperion-sha256" HYP_DXC_ID)
file(READ "${HYP_DEPS}/spirv-cross/.hyperion-sha256" HYP_CROSS_ID)
target_compile_definitions(hyperion_shaders PRIVATE HYP_TOOLCHAIN_ID="${HYP_DXC_ID}-${HYP_CROSS_ID}")
