set(HYP_DEPS "${PROJECT_SOURCE_DIR}/out/deps" CACHE PATH "Locked dependency sources")
file(READ "${PROJECT_SOURCE_DIR}/dependencies.lock.json" HYP_LOCK)
foreach(name spdlog mimalloc tracy onetbb sdl json glm cgltf stb tinyexr spirv-cross d3d12ma imgui implot dxc)
  if(NOT EXISTS "${HYP_DEPS}/${name}/.hyperion-sha256")
    message(FATAL_ERROR "Missing ${name}. Run python tools/Bootstrap.py")
  endif()
  file(READ "${HYP_DEPS}/${name}/.hyperion-sha256" actual)
  string(JSON expected GET "${HYP_LOCK}" "${name}" sha256)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "Dependency ${name} does not match dependencies.lock.json")
  endif()
endforeach()
function(hyp_dependency name)
  if(NOT EXISTS "${HYP_DEPS}/${name}/.hyperion-sha256")
    message(FATAL_ERROR "Missing dependency ${name}. Run python tools/Bootstrap.py --only ${name}")
  endif()
  add_subdirectory("${HYP_DEPS}/${name}" "${PROJECT_BINARY_DIR}/deps/${name}" EXCLUDE_FROM_ALL SYSTEM)
endfunction()
set(SPDLOG_BUILD_EXAMPLE OFF CACHE BOOL "" FORCE)
set(SPDLOG_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(MI_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(MI_BUILD_SHARED OFF CACHE BOOL "" FORCE)
set(MI_OVERRIDE OFF CACHE BOOL "" FORCE)
set(MI_BUILD_OBJECT OFF CACHE BOOL "" FORCE)
set(TRACY_ENABLE ON CACHE BOOL "" FORCE)
set(TRACY_ON_DEMAND ON CACHE BOOL "" FORCE)
hyp_dependency(spdlog)
hyp_dependency(mimalloc)
hyp_dependency(tracy)
set(TBB_TEST OFF CACHE BOOL "" FORCE)
set(TBB_EXAMPLES OFF CACHE BOOL "" FORCE)
set(TBB_STRICT OFF CACHE BOOL "" FORCE)
set(TBBMALLOC_BUILD OFF CACHE BOOL "" FORCE)
set(TBB_ENABLE_IPO OFF CACHE BOOL "" FORCE)
hyp_dependency(onetbb)
set(JSON_BuildTests OFF CACHE BOOL "" FORCE)
hyp_dependency(json)
set(SDL_SHARED OFF CACHE BOOL "" FORCE)
set(SDL_STATIC ON CACHE BOOL "" FORCE)
set(SDL_TESTS OFF CACHE BOOL "" FORCE)
set(SDL_TEST_LIBRARY OFF CACHE BOOL "" FORCE)
set(SDL_EXAMPLES OFF CACHE BOOL "" FORCE)
foreach(feature AUDIO GPU RENDER JOYSTICK HAPTIC HIDAPI SENSOR CAMERA)
  set(SDL_${feature} OFF CACHE BOOL "" FORCE)
endforeach()
hyp_dependency(sdl)
set(GLM_BUILD_LIBRARY OFF CACHE BOOL "" FORCE)
set(GLM_BUILD_TESTS OFF CACHE BOOL "" FORCE)
hyp_dependency(glm)
add_library(hyp_miniz STATIC "${HYP_DEPS}/tinyexr/deps/miniz/miniz.c")
target_include_directories(hyp_miniz SYSTEM PUBLIC "${HYP_DEPS}/tinyexr/deps/miniz")
set(SPIRV_CROSS_CLI OFF CACHE BOOL "" FORCE)
set(SPIRV_CROSS_ENABLE_TESTS OFF CACHE BOOL "" FORCE)
set(SPIRV_CROSS_ENABLE_HLSL OFF CACHE BOOL "" FORCE)
set(SPIRV_CROSS_ENABLE_CPP OFF CACHE BOOL "" FORCE)
set(SPIRV_CROSS_ENABLE_REFLECT OFF CACHE BOOL "" FORCE)
set(SPIRV_CROSS_ENABLE_C_API OFF CACHE BOOL "" FORCE)
set(SPIRV_CROSS_ENABLE_UTIL OFF CACHE BOOL "" FORCE)
set(SPIRV_CROSS_SKIP_INSTALL ON CACHE BOOL "" FORCE)
hyp_dependency(spirv-cross)
add_library(hyp_d3d12ma STATIC "${HYP_DEPS}/d3d12ma/src/D3D12MemAlloc.cpp")
target_include_directories(hyp_d3d12ma SYSTEM PUBLIC "${HYP_DEPS}/d3d12ma/include")
target_compile_definitions(hyp_d3d12ma PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
target_link_libraries(hyp_d3d12ma PRIVATE d3d12 dxgi dxguid)
add_library(hyp_imgui STATIC "${HYP_DEPS}/imgui/imgui.cpp" "${HYP_DEPS}/imgui/imgui_draw.cpp" "${HYP_DEPS}/imgui/imgui_tables.cpp" "${HYP_DEPS}/imgui/imgui_widgets.cpp")
target_include_directories(hyp_imgui SYSTEM PUBLIC "${HYP_DEPS}/imgui")
add_library(hyp_implot STATIC "${HYP_DEPS}/implot/implot.cpp" "${HYP_DEPS}/implot/implot_items.cpp")
target_include_directories(hyp_implot SYSTEM PUBLIC "${HYP_DEPS}/implot")
target_link_libraries(hyp_implot PRIVATE hyp_imgui)
