set_property(GLOBAL PROPERTY USE_FOLDERS ON)
set_property(DIRECTORY "${PROJECT_SOURCE_DIR}" PROPERTY VS_STARTUP_PROJECT hyperion_viewer)

function(hyp_vs_vendor_folders directory)
  get_property(targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
  foreach(target IN LISTS targets)
    get_target_property(owned ${target} HYP_OWNED)
    if(NOT owned)
      set_target_properties(${target} PROPERTIES FOLDER "ThirdParty")
    endif()
  endforeach()
  get_property(children DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
  foreach(child IN LISTS children)
    hyp_vs_vendor_folders("${child}")
  endforeach()
endfunction()
hyp_vs_vendor_folders("${PROJECT_SOURCE_DIR}")
if(BUILD_TESTING)
  set_target_properties(hyperion_check PROPERTIES FOLDER "Hyperion/Tests")
endif()
