# IDE-only metadata: runtime and shader compilation still use the engine's normal paths.
set_property(GLOBAL PROPERTY USE_FOLDERS ON)
set_property(DIRECTORY "${PROJECT_SOURCE_DIR}" PROPERTY VS_STARTUP_PROJECT hyperion_viewer)

function(hyp_vs_sources target)
  target_sources(${target} PRIVATE ${ARGN})
  get_target_property(sources ${target} SOURCES)
  set(absolute_sources "")
  foreach(source IN LISTS sources)
    get_filename_component(absolute "${source}" ABSOLUTE BASE_DIR "${PROJECT_SOURCE_DIR}")
    list(APPEND absolute_sources "${absolute}")
  endforeach()
  source_group(TREE "${PROJECT_SOURCE_DIR}" FILES ${absolute_sources})
  set_target_properties(${target} PROPERTIES FOLDER "Hyperion")
endfunction()
hyp_vs_sources(hyperion_core include/hyperion/Core.h)
hyp_vs_sources(hyperion_tasks include/hyperion/TaskSystem.h)
hyp_vs_sources(hyperion_config include/hyperion/Config.h include/hyperion/Plugins.h)
hyp_vs_sources(hyperion_platform include/hyperion/Platform.h)
hyp_vs_sources(hyperion_assets include/hyperion/Assets.h include/hyperion/Math.h)
hyp_vs_sources(hyperion_shaders include/hyperion/ShaderCompiler.h)
hyp_vs_sources(hyperion_rhi include/hyperion/RHI.h)
hyp_vs_sources(hyperion_render include/hyperion/RenderGraph.h)
hyp_vs_sources(hyperion_gui include/hyperion/Gui.h)
hyp_vs_sources(hyperion_debug_ui include/hyperion/DebugUI.h)

set(shader_sources shaders/Common.hlsli shaders/Triangle.hlsl shaders/Gui.hlsl)
set_source_files_properties(${shader_sources} PROPERTIES HEADER_FILE_ONLY TRUE)
hyp_vs_sources(hyperion_viewer ${shader_sources} experiments/Triangle.json README.md
  docs/Architecture.md docs/Dependencies.md docs/VisualStudio.md docs/CodingStyle.md
  AGENTS.md .clang-format .clang-tidy .editorconfig .gitattributes
  GenerateSolution.cmd tools/GenerateSolution.ps1 tools/VisualStudio.py tools/CheckStyle.py)
set_target_properties(hyperion_viewer PROPERTIES FOLDER "Applications"
  VS_DEBUGGER_WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}")

if(BUILD_TESTING)
  foreach(target core_tests task_tests config_tests asset_tests shader_tests graph_tests gui_tests)
    hyp_vs_sources(${target} tests/TestSupport.h)
    set_target_properties(${target} PROPERTIES FOLDER "Tests"
      VS_DEBUGGER_WORKING_DIRECTORY "${PROJECT_BINARY_DIR}")
  endforeach()
  set_target_properties(hyperion_check PROPERTIES FOLDER "Tests")
endif()

function(hyp_vs_vendor_folders directory)
  get_property(targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
  foreach(target IN LISTS targets)
    set_target_properties(${target} PROPERTIES FOLDER "ThirdParty")
  endforeach()
  get_property(children DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
  foreach(child IN LISTS children)
    hyp_vs_vendor_folders("${child}")
  endforeach()
endfunction()
get_property(vendor_directories DIRECTORY "${PROJECT_SOURCE_DIR}" PROPERTY SUBDIRECTORIES)
foreach(directory IN LISTS vendor_directories)
  hyp_vs_vendor_folders("${directory}")
endforeach()
set_target_properties(hyp_miniz hyp_d3d12ma hyp_imgui hyp_implot PROPERTIES FOLDER "ThirdParty")
