add_executable(hyperion_viewer Private/Main.cpp Private/Viewer.manifest)
hyp_executable(hyperion_viewer)
target_sources(hyperion_viewer PRIVATE "${PROJECT_SOURCE_DIR}/Source/Applications/Resources/Hyperion.rc")
target_include_directories(hyperion_viewer PRIVATE "${PROJECT_SOURCE_DIR}/Source/Applications/Resources")
target_link_libraries(hyperion_viewer PRIVATE hyperion_viewer_plugin hyperion_rhi_d3d12 hyperion_core)
target_compile_definitions(hyperion_viewer PRIVATE HYP_SOURCE_DIR="${PROJECT_SOURCE_DIR}")
set_target_properties(hyperion_viewer PROPERTIES VS_DEBUGGER_WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}")
if(CMAKE_GENERATOR MATCHES "^Visual Studio")
  include("${PROJECT_SOURCE_DIR}/cmake/ViewerContent.cmake")
endif()
